#!/usr/bin/env bash

mod_ethernet () {
	local OPTIND arg flag_l flag_i flag_f
	while getopts ':l:i:f:' arg; do
		case "$arg" in
			l) flag_l="$OPTARG" ;;
			i) flag_i=$(icon "$OPTARG") ;;
			f) flag_f="$OPTARG" ;;
		esac
	done
	shift $((OPTIND-1))
	local -r LABEL=$flag_l
	local -r ICON=${flag_i:-$(icon 'NETWORK_WIRED')}
	local -r FREQ=${flag_f:-30}
	for ((;;)); do
		local ip_address=$(ifconfig enp3s0 | grep -Eo 'inet \S+' |\
			sed 's/inet //g')
		if [[ -n "$ip_address" ]]; then
			print_module "$1" "$LABEL$ICON$ip_address"
		else
			print_module "$1" "$(print_nothing)"
		fi
		(( GLOBAL_STATUSBAR_MODE )) && sleep "$FREQ" || break
	done
}
