#!/usr/bin/env bash

mod_cpu () {
	local OPTIND arg flag_l flag_i flag_f
	while getopts ':l:i:f:' arg; do
		case "$arg" in
			l) flag_l="$OPTARG" ;;
			i) flag_i=$(icon "$OPTARG") ;;
			f) flag_f="$OPTARG" ;;
		esac
	done
	shift $((OPTIND-1))
	local -r LABEL=$flag_l
	local -r ICON=${flag_i:-$(icon 'MICROCHIP')}
	local -r FREQ=${flag_f:-10}
	local -r CORES=$(lscpu | grep -E '^CPU\(s\):' | awk '{print $2}')
	for ((;;)); do
		local percentages=$(ps -eo pcpu | awk\
			"BEGIN {sum=0.0f} {sum+=\$1} END {printf \"%.1f:%.1f\",sum/$CORES,sum}"\
		)
		local usage="${percentages#*:}"
		local adjusted_usage="${percentages%%:*}"
		if (( $(printf '%.0f' "$usage") >= 100 )); then
			print_module "$1" "$LABEL$ICON$adjusted_usage% ($usage%)"
		else
			print_module "$1" "$LABEL$ICON$adjusted_usage%"
		fi
		(( GLOBAL_STATUSBAR_MODE )) && sleep "$FREQ" || break
	done
}
