#!/usr/bin/env bash

mod_used_space_root () {
	local OPTIND arg flag_l flag_f
	while getopts ':l:f:' arg; do
		case "$arg" in
			l) flag_l="$OPTARG" ;;
			f) flag_f="$OPTARG" ;;
		esac
	done
	shift $((OPTIND-1))
	local -r LABEL=$flag_l
	local -r FREQ=${flag_f:-60}
	for ((;;)); do
		local output=$(df | grep -Po '\d+%(?=\s+/$)')
		print_module "$1" "$LABEL$output used"
		(( GLOBAL_STATUSBAR_MODE )) && sleep "$FREQ" || break
	done
}
